version: "3.5"

volumes:
  data:

services:
  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=12345
    volumes:
      - data:/var/lib/postgresql/data
