export enum ApiError {
  BAD_REQUEST = "BAD_REQUEST",
  BUSINESS = "BUSINESS",
  NOT_FOUND = "NOT_FOUND",
  VALIDATION = "VALIDATION",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  UNAUTHORIZED = "UNAUTHORIZED"
}
